spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://43.201.37.133:3306/DB202112304"
    username: user202112304
    password: !mynameis202112304
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
